import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google"; // 폰트를 불러오는 것
import "./globals.css";
import Navbar from "@/components/navgar";

const inter = Noto_Sans_KR({ subsets: ["latin"] }); // 여기에서 폰트 라이브러리 불러오기

export const metadata: Metadata = {
  title: "Hello World!", //맨 위에 타이틀 그 진짜 맨 위
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Navbar />
        <div style={{ paddingTop: "50px" }} > 
          {children}
        </div>
        </body>
    </html>
  );
}
